//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 05:20:19 PM CEST 
//


package pl.db;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for question complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="question"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="answer1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="answer2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="answer3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="answer4" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="correctAnswer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "question", propOrder = {
    "content",
    "answer1",
    "answer2",
    "answer3",
    "answer4",
    "correctAnswer"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
public class Question {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    protected String content;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    protected String answer1;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    protected String answer2;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    protected String answer3;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    protected String answer4;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    protected String correctAnswer;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the answer1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public String getAnswer1() {
        return answer1;
    }

    /**
     * Sets the value of the answer1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public void setAnswer1(String value) {
        this.answer1 = value;
    }

    /**
     * Gets the value of the answer2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public String getAnswer2() {
        return answer2;
    }

    /**
     * Sets the value of the answer2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public void setAnswer2(String value) {
        this.answer2 = value;
    }

    /**
     * Gets the value of the answer3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public String getAnswer3() {
        return answer3;
    }

    /**
     * Sets the value of the answer3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public void setAnswer3(String value) {
        this.answer3 = value;
    }

    /**
     * Gets the value of the answer4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public String getAnswer4() {
        return answer4;
    }

    /**
     * Sets the value of the answer4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public void setAnswer4(String value) {
        this.answer4 = value;
    }

    /**
     * Gets the value of the correctAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public String getCorrectAnswer() {
        return correctAnswer;
    }

    /**
     * Sets the value of the correctAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-01T05:20:19+02:00", comments = "JAXB RI v2.3.0")
    public void setCorrectAnswer(String value) {
        this.correctAnswer = value;
    }

}
